#!/usr/bin/python
import math   # This will import math module

def find_next_square(sq):
    # Return the next square if sq is a square, -1 otherwise
    if (math.sqrt(sq)-int(math.sqrt(sq))) == 0:
        sq +=1
        while (math.sqrt(sq)-int(math.sqrt(sq))) != 0:
            sq +=1
        return sq
    else: return -1

print find_next_square(16)